services:
  - type: web
    name: emotion-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    branch: main
    autoDeploy: true
